# NumPy Clase 01

In [3]:
import numpy as np

In [4]:
 L1 = [1,2,3,4,5,6]#Creamos una lista

In [7]:
x1 = np.array(L1) #Creamos un array de Numpy a partir de una Lista
x1

array([1, 2, 3, 4, 5, 6])

In [8]:
x2 = np.array(L1, dtype= 'float32') #Para espedificar el tipo de dato

In [10]:
x2

array([1., 2., 3., 4., 5., 6.], dtype=float32)

### Tipos de datos

-bool_

-int_, intc, intp, int8, int16, int32, int64

-uint8, uint16, uint32, unint64

-float_, float16, float32, float64

-complex_, complex64, complex128


In [13]:
np.zeros((3,4)) #Arreglo de ceros


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((3,4)) #Arreglo de unos

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.arange(10) #Arra de 10 elementos

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(3, 12, dtype='float') #Especificando extremos y tipo

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [24]:
np.arange(4,5,0.1) #De 4 a 5 en saltos de 0.1

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [25]:
np.linspace(1.,7.,12)#Crear un arreglo del 1 al 7 en 12 partes con la misma distancia entre uno y otro

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [26]:
np.eye(5) #Matriz identidad de 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
x = np.zeros((8,3)) #PRIMERO: Creamos un arerglo de ceros de 8x3
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
x.reshape((6,4)) #Reestribuimos los elementos de x (Debe contener el mismo número de elementos)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
y = np.array([[1,2,3,4],[5,6,7,8]]) #PRIMERO: Creamos un arreglo con los elementos indicados
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
np.ravel(y) #Aplana o colapsa el arreglo de y (ravel trabaja con el mismo arreglo)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
y.flatten() #Aplana o colapsa el arreglo de y (flatten crea una copia de y para aplanarlo)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
np.transpose(y) #Trasponer la matriz

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [42]:
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
np.resize(y,(5,3)) #Redimensiona el arreglo y pero si se pasa del número de elementos los repetira

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios

In [49]:
x1 = np.arange(5,120,1)
x1

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [59]:
x2 = np.arange(0, 16)
x2
x3 = x2.reshape((4,4))
x3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
x4 = np.eye(7)
x4

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [61]:
x5 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
x5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
x6 = x5.reshape((5,4))
x6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [65]:

x7 = np.linspace(0, 5,20)
x7

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])